 export const MenuItems = [
  {
    FoodName: "Scrambled Eggs",
    Price: 12,
    GlutenFree: true,
    Meal: "Breakfast",
    Cheap: true,
    Image: "/scrambled.jpg",
  },
  {
    FoodName: "Ham Sandwich",
    Price: 13,
    GlutenFree: true,
    Meal: "Lunch",
    Cheap: true,
    Image: "/sandwich.jpg",
  },
  {
    FoodName: "Ribeye Steak",
    Price: 40,
    GlutenFree: false,
    Meal: "Dinner",
    Cheap: false,
    Image: "/ribeye.jpg",
  },
  {
    FoodName: "Burger",
    Price: 22,
    GlutenFree: false,
    Meal: "Lunch",
    Cheap: false,
    Image: "/hamburger.jpg",
  },
  {
    FoodName: "Chicken Sandwich",
    Price: 17,
    GlutenFree: true,
    Meal: "Lunch",
    Cheap: true,
    Image: "/chicksandwich.webp",
  },
  {
    FoodName: "Salmon",
    Price: 23,
    GlutenFree: true,
    Meal: "Dinner",
    Cheap: false,
    Image: "/salmon.jpg",
  },
  {
    FoodName: "Lamb Chops",
    Price: 30,
    GlutenFree: false,
    Meal: "Dinner",
    Cheap: false,
    Image: "/lambchop.jpg",
  },
  {
    FoodName: "Lamb Gyro",
    Price: 17,
    GlutenFree: false,
    Meal: "Lunch",
    Cheap: true,
    Image: "/gyro.jpg",
  },
  {
    FoodName: "Pancakes",
    Price: 14,
    GlutenFree: false,
    Meal: "Breakfast",
    Cheap: true,
    Image: "/pancakes.jpg",
  },
  {
    FoodName: "French Toast",
    Price: 21,
    GlutenFree: false,
    Meal: "Breakfast",
    Cheap: false,
    Image: "/breakfast.jpg",
  },
  {
    FoodName: "English Breakfast",
    Price: 30,
    GlutenFree: false,
    Meal: "Breakfast",
    Cheap: false,
    Image: "/engbreakfast.jpg",
  },
  {
    FoodName: "Sushi",
    Price: 45,
    GlutenFree: true,
    Meal: "Lunch",
    Cheap: false,
    Image: "/sushi.jpg",
  },
  {
    FoodName: "House Salad",
    Price: 15,
    GlutenFree: true,
    Meal: "Lunch",
    Cheap: true,
    Image: "/salad.jpg",
  },
  {
    FoodName: "Seafood Platter",
    Price: 55,
    GlutenFree: true,
    Meal: "Dinner",
    Cheap: false,
    Image: "/seafood.jpg",
  },
  {
    FoodName: "Beef Wellington",
    Price: 44,
    GlutenFree: false,
    Meal: "Dinner",
    Cheap: false,
    Image: "/beef-wellington.jpg",
  },
  {
    FoodName: "Chicken and Rice",
    Price: 22,
    GlutenFree: true,
    Meal: "Dinner",
    Cheap: false,
    Image: "/chickrice.jpg",
  },
  {
    FoodName: "Tacos",
    Price: 17,
    GlutenFree: false,
    Meal: "Lunch",
    Cheap: true,
    Image: "/tacos.jpg",
  },
  {
    FoodName: "Spanakopita",
    Price: 34,
    GlutenFree: false,
    Meal: "Lunch",
    Cheap: false,
    Image: "/spanakopita.jpg",
  },
];